'\" t
.\"     Title: bfsync-clone
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 06/30/2018
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "BFSYNC\-CLONE" "1" "06/30/2018" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
bfsync-clone \- Clone a bfsync repo from a bfsync master repo
.SH "SYNOPSIS"
.sp
.nf
\fIbfsync clone\fR [\-u] [\-c <cache_size_mb>] [\-\-rsh <remote_shell>]
             <repo> [<dest\-dir>]
.fi
.SH "DESCRIPTION"
.sp
Initialize new cloned bfsync repo from bfsync master repo\&. If <dest\-dir> is not specified, bfsync clone will generate a directory name from the repository name, otherwise it will clone into the directory <dest\-dir>\&.
.SH "OPTIONS"
.PP
\-u
.RS 4
If
\-u
is given, bfsync clone will set the
"use\-uid\-gid"
option in the config file for the cloned repository to 1\&. This means that upon mount, the user id settings and group id settings for files/directories will be taken from the repository\&. This will only make sense if all machines that access the data have the same uid/gid numbers\&. The default (without
\-u) is not to use the uid/gid numbers, which should be perfect for almost every use case except for backups\&.
.RE
.PP
\-c <cache_size_mb>
.RS 4
The cache size is the amount of shared memory that will be used as database cache size\&. It defaults to 16 MB, which is fine for repositories that contain a small amount of files\&. For synchronizing big files between different hosts, that will usually work\&. If the amount of files is large (> 100\&.000), you need a larger cache size\&. At least 100 MB cache per 1\&.000\&.000 files stored should be used, more is better, if you can afford it\&.
.RE
.PP
\-\-rsh <remote_shell>
.RS 4
This option can be used to set the remote shell used to connect the host; it defaults to ssh\&.
.RE
