.TH "BFSYNCFS" "1" "2012\-09\-05" "Revision 776" "bfsync Manual Page"

.SH NAME

bfsyncfs - FuSE filesystem to be used with bfsync big file synchronization tool

.SH SYNOPSIS

\fBbfsyncfs\fR \fI[<options>]\fR \fI<repo>\fR \fI<mount-point>\fR

.SH DESCRIPTION

\fBbfsyncfs\fR is a FuSE filesystem which can be used to modify the contents of a bfsync repsitory. To use it, you need a local bfsync checkout (created with bfsync clone) and a mount point, which must be empty before running bfsyncfs. Upon successful mount, the mount point directory will be used to display the contents of the repository and modifications can be made with any program that can operate on files/directories, like a filemanager, rsync or regular shell commands like cp or mv.

Note that changes only become permanent after using bfsync commit. Other bfsync commands can be used to synchronize the repository history/contents with other bfsync repos.

.SH OPTIONS
.TP
\fB<repo>\fR
The repository argument should point to a local bfsync checkout (created with bfsync clone).
.PP
.TP
\fB<mount-point>\fR
The mount point should be an empty directory.
.PP
.TP
\fB-a\fR
Allows other users to access the mounted filesystem (this sets the -oallow_other option). Without this option, the contents of the filesystem will only be readable/writeable by the user that mounted it.
.PP
.TP
\fB-c\fR
Enable FUSE attribute caching. This improves the overall performance of bfsyncfs somewhat. However, in some rare cases the filesystem will no longer return the correct result to the userspace process, therefore it is not enabled by default.
.PP
.TP
\fB-f\fR
Run the filesystem as foreground process. Without this option, bfsyncfs will be started as background process.
.PP
.TP
\fB-d\fR
Enables debugging output, this option is mainly useful during development/debugging.
.PP

.SH THE .BFSYNC DIRECTORY

Once a repository is mounted, all data contained in the current version of the repository will be available through the mount point. However, one additional directory will show up in the file system, the ".bfsync" directory. Within the .bfsync directory, all previous versions of the file system are available inside the commits directory. So if you access the contents of .bfsync/commits/8, this directory will contain the contents of the repository version 8. It is not possible to modify old commits, the .bfsync directory is only for reading.

.SH CONFIGURATION

There are configuration options from the repository config file that affect bfsyncfs, they are documented in the bfsync manual page.

.SH SEE ALSO

bfsync.1 <http://testbit.eu/Bfsync.1>

