'\" t
.\"     Title: bfsync-check-integrity
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 06/30/2018
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "BFSYNC\-CHECK\-INTEG" "1" "06/30/2018" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
bfsync-check-integrity \- Check repository integrity
.SH "SYNOPSIS"
.sp
.nf
\fIbfsync check\-integrity\fR [\-i <time_interval>]
.fi
.SH "DESCRIPTION"
.sp
This commands runs some basic integrity checks on the repository\&. If this check fails, the database is not consistent\&. Usually this means either some kind of hardware problem or a software bug occurred in the past\&.
.SH "OPTIONS"
.PP
\-i <time_interval>
.RS 4
By using the \-i option, which can be
weekly
or
daily, the integrity check will be skipped if it already was performed in this time interval\&.
.RE
